// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfjgAL6vgEjAhjPSzk4jFeW0qtNookfek',
    appId: '1:574620768799:web:173da77fd84f4b509f532a',
    messagingSenderId: '574620768799',
    projectId: 'nsc-database-879ff',
    authDomain: 'nsc-database-879ff.firebaseapp.com',
    databaseURL:
        'https://nsc-database-879ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nsc-database-879ff.appspot.com',
    measurementId: 'G-3ESZTTM2GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkNufByTC-xZ5202rdWGOAWK2JtMjRqoo',
    appId: '1:574620768799:android:994a0e3ef4aaedaf9f532a',
    messagingSenderId: '574620768799',
    projectId: 'nsc-database-879ff',
    databaseURL:
        'https://nsc-database-879ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nsc-database-879ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANV8_227zZS73gni3JZ7TgMc3QTc5L3hc',
    appId: '1:574620768799:ios:460b1ee6fed09f689f532a',
    messagingSenderId: '574620768799',
    projectId: 'nsc-database-879ff',
    databaseURL:
        'https://nsc-database-879ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nsc-database-879ff.appspot.com',
    iosClientId:
        '574620768799-vua6lhstbf6pg1es134ui0eau87rqild.apps.googleusercontent.com',
    iosBundleId: 'com.example.nsc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANV8_227zZS73gni3JZ7TgMc3QTc5L3hc',
    appId: '1:574620768799:ios:460b1ee6fed09f689f532a',
    messagingSenderId: '574620768799',
    projectId: 'nsc-database-879ff',
    databaseURL:
        'https://nsc-database-879ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nsc-database-879ff.appspot.com',
    iosClientId:
        '574620768799-vua6lhstbf6pg1es134ui0eau87rqild.apps.googleusercontent.com',
    iosBundleId: 'com.example.nsc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfjgAL6vgEjAhjPSzk4jFeW0qtNookfek',
    appId: '1:574620768799:web:3aaba8755cc164e49f532a',
    messagingSenderId: '574620768799',
    projectId: 'nsc-database-879ff',
    authDomain: 'nsc-database-879ff.firebaseapp.com',
    databaseURL:
        'https://nsc-database-879ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nsc-database-879ff.appspot.com',
    measurementId: 'G-02GBH9NX9C',
  );
}
